// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuAjItyCV87hs4kBoFeMDeBfSuGXRN4yg',
    appId: '1:953784361580:web:88b4218272dca57a902e49',
    messagingSenderId: '953784361580',
    projectId: 'todo-getx-1d164',
    authDomain: 'todo-getx-1d164.firebaseapp.com',
    storageBucket: 'todo-getx-1d164.firebasestorage.app',
    measurementId: 'G-J1NTQT9V7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI024D6biD8CWWycs7e7EXPcA4NNuy73c',
    appId: '1:953784361580:android:d8ed96347526f5c4902e49',
    messagingSenderId: '953784361580',
    projectId: 'todo-getx-1d164',
    storageBucket: 'todo-getx-1d164.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_0kNrNbAFQk4whKj4Dzehus59bjq2Tk4',
    appId: '1:953784361580:ios:8ddf22e5d005fc1a902e49',
    messagingSenderId: '953784361580',
    projectId: 'todo-getx-1d164',
    storageBucket: 'todo-getx-1d164.firebasestorage.app',
    iosBundleId: 'com.example.todoGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_0kNrNbAFQk4whKj4Dzehus59bjq2Tk4',
    appId: '1:953784361580:ios:8ddf22e5d005fc1a902e49',
    messagingSenderId: '953784361580',
    projectId: 'todo-getx-1d164',
    storageBucket: 'todo-getx-1d164.firebasestorage.app',
    iosBundleId: 'com.example.todoGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuAjItyCV87hs4kBoFeMDeBfSuGXRN4yg',
    appId: '1:953784361580:web:c29d8dd0a8db4e84902e49',
    messagingSenderId: '953784361580',
    projectId: 'todo-getx-1d164',
    authDomain: 'todo-getx-1d164.firebaseapp.com',
    storageBucket: 'todo-getx-1d164.firebasestorage.app',
    measurementId: 'G-2XE4CZE55S',
  );
}
